name: Build and Push to Sylabs
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sylabs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Singularity
        run: |
          sudo apt-get update
          sudo apt-get install -y wget uuid-runtime libgpgme11
          export SY_VER=4.1.1 
          wget https://github.com/sylabs/singularity/releases/download/v${SY_VER}/singularity-ce_${SY_VER}-focal_amd64.deb
          sudo apt-get install -y ./singularity-ce_${SY_VER}-focal_amd64.deb

      - name: Build and Push
        env:
          SYLABS_TOKEN: ${{ secrets.SYLABS_TOKEN }}
        run: |
          sudo singularity build caat.sif images/caat.def

          singularity remote add --no-login SylabsCloud cloud.sylabs.io
          singularity remote use SylabsCloud
          echo "$SYLABS_TOKEN" | singularity remote login --password-stdin

          IMAGE_PATH="library://prameshsharma25/caat-project/caat:latest"
          
          singularity library delete -f $IMAGE_PATH || echo "Nothing to delete"
          
          singularity push caat.sif $IMAGE_PATH
